env:
  decimation: 2
  episode_length: 5.0 # [sec]
  action_scale: 100.0 # [N]
  action_space: 7
  angle_obs_space: 7
  velocity_obs_space: 7
  state_space: 0
scene:
  num_envs: 4096
  env_spacing: 10.0
  replicate_physics: True
  clone_in_fabric: True
  wall_thickness: 0.1 # [M]
  sensor:
    camera_height: 480 # [pixels]
    camera_width: 640 # [pixels]
    force_history_length: 5
event:
  panda:
    material:
      static_friction_range: [0.5, 1.5]
      dynamic_friction_range: [1.0, 1.0]
      restitution_range: [1.0, 1.0]
      num_buckets: 250
    actuator_gains:
      stiffness_distribution_params: [0.75, 1.5]
      damping_distribution_params: [0.3, 3.0]
    mass:
      mass_distribution_params: [0.85, 1.15]
    joint_params:
      friction_distribution_params: [0.85, 1.15]
      armature_distribution_params: [0.75, 1.25]
      force_range: [-2.0, 2.0]
      torque_range: [-0.4, 0.4]
      position_range: [0.7, 1.3]
      velocity_range: [0.5, 1.5]
  physics:
    gravity:
      gravity_distribution_params: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.4]]
reward:
  scale_grasp: 1.0
  scale_duration: -0.1
  scale_distance: 0.1
  scale_drop: -1.5
  scale_contact: 0.5